### ISSUE TITLE
🚀 [feature] 선호 팀/리그의 추가 및 삭제 기능 구현

### ISSUE THREAD

**Issue by koojun99** [koojun99/Football_Community#17]
# 🤖 기능 개요

선호 팀/리그의 추가 및 삭제 기능 구현
## ✅ Todo
- [x] 선호하는 팀/리그 추가하기
- [x] 선호하는 팀/리그 삭제하기
- [x] 선호하는 팀/리그 목록 조회하기
- [x] 알림 여부 선택
