### ISSUE TITLE
🚀 [feature] 경기 관련 기능

### ISSUE THREAD

**Issue by koojun99** [koojun99/Football_Community#19]
# 🤖 기능 개요

축구 경기 관련 기능 구현
## ✅ Todo
- [x] 특정 팀의 경기 불러오기
- [x] 특정 리그의 경기 불러오기
- [x] 특정 경기의 세부 정보
